name: Build executables

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  VERSION_MAJOR: 1
  VERSION_MINOR: 0
  VERSION_PATCH: 0
  VERSION_BUILD: 0
  AUTHOR: "Adriel Chandra"
  COMPANY: "Kaiei Tokiyasu"
  DESCRIPTION: "Menu-driven command-line tool for HR data processing and reporting"
  PRODUCT_NAME: "Chibi HR"
  INTERNAL_NAME: "chibihr"
  ORIGINAL_FILENAME: "chibi-HR"

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - run: python -m pip install --upgrade pip
      - run: pip install -r requirements.txt

      - name: Generate version.txt
        run: |
          cat <<EOF > version.txt
          # UTF-8
          #
          # For more details about fixed file info 'ffi' see:
          # http://msdn.microsoft.com/en-us/library/ms646997.aspx
          VSVersionInfo(
            ffi=FixedFileInfo(
              filevers=($$VERSION_MAJOR, $$VERSION_MINOR, $$VERSION_PATCH, $$VERSION_BUILD),
              prodvers=($$VERSION_MAJOR, $$VERSION_MINOR, $$VERSION_PATCH, $$VERSION_BUILD),
              mask=0x3f,
              flags=0x0,
              OS=0x4,
              fileType=0x1,
              subtype=0x0,
              date=(0, 0)
              ),
            kids=[
              StringFileInfo(
                [
                StringTable(
                  '040904B0',
                  [
                      StringStruct('CompanyName', '$$COMPANY'),
                      StringStruct('FileDescription', '$$DESCRIPTION'),
                      StringStruct('FileVersion', '$$VERSION_MAJOR.$$VERSION_MINOR.$$VERSION_PATCH.$$VERSION_BUILD'),
                      StringStruct('InternalName', '$$INTERNAL_NAME'),
                      StringStruct('LegalCopyright', '$$COMPANY'),
                      StringStruct('OriginalFilename', '$$ORIGINAL_FILENAME.exe'),
                      StringStruct('ProductName', '$$PRODUCT_NAME'),
                      StringStruct('ProductVersion', '$$VERSION_MAJOR.$$VERSION_MINOR.$$VERSION_PATCH.$$VERSION_BUILD'),
                      StringStruct('Comments', 'Author: $$AUTHOR')
                  ]),
                ]),
              VarFileInfo([VarStruct('Translation', [1033, 1200])])
            ]
          )
          EOF

      - name: Build Windows executable
        run: |
          pyinstaller --onefile --version-file=version.txt --name chibi-HR main.py

      - uses: actions/upload-artifact@v4
        with:
          name: windows-executable
          path: dist/chibi-HR.exe

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - run: python -m pip install --upgrade pip
      - run: pip install -r requirements.txt

      - name: Inject version info in app (optional)
        run: |
          echo "__version__ = '${VERSION_MAJOR}.${VERSION_MINOR}.${VERSION_PATCH}.${VERSION_BUILD}'" > version.py

      - name: Build Linux executable
        run: |
          pyinstaller --onefile --name chibi-HR main.py

      - uses: actions/upload-artifact@v4
        with:
          name: linux-executable
          path: dist/chibi-HR
